version: "3.8"
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db # 数据文件写入当前项目下的 /data路径中
